// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3kdYP2q9hQb0xnBi87Q1X4ucSCPdqmT4',
    appId: '1:972237145466:web:f724d3aff2f77036ff02c3',
    messagingSenderId: '972237145466',
    projectId: 'fir-auth-sample-2d2cb',
    authDomain: 'fir-auth-sample-2d2cb.firebaseapp.com',
    storageBucket: 'fir-auth-sample-2d2cb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCJFNTaOnjdi-SmIwISzORG2kOY2qWOrc',
    appId: '1:972237145466:android:a0e25e00c2efee93ff02c3',
    messagingSenderId: '972237145466',
    projectId: 'fir-auth-sample-2d2cb',
    storageBucket: 'fir-auth-sample-2d2cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0AQdwBlO_T1ERCvs7XALuMb70qyzCIzI',
    appId: '1:972237145466:ios:b47b731357588389ff02c3',
    messagingSenderId: '972237145466',
    projectId: 'fir-auth-sample-2d2cb',
    storageBucket: 'fir-auth-sample-2d2cb.firebasestorage.app',
    iosBundleId: 'com.example.1FirebaseAuthSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0AQdwBlO_T1ERCvs7XALuMb70qyzCIzI',
    appId: '1:972237145466:ios:b47b731357588389ff02c3',
    messagingSenderId: '972237145466',
    projectId: 'fir-auth-sample-2d2cb',
    storageBucket: 'fir-auth-sample-2d2cb.firebasestorage.app',
    iosBundleId: 'com.example.1FirebaseAuthSample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3kdYP2q9hQb0xnBi87Q1X4ucSCPdqmT4',
    appId: '1:972237145466:web:ea0414ad4a357d01ff02c3',
    messagingSenderId: '972237145466',
    projectId: 'fir-auth-sample-2d2cb',
    authDomain: 'fir-auth-sample-2d2cb.firebaseapp.com',
    storageBucket: 'fir-auth-sample-2d2cb.firebasestorage.app',
  );
}